server:
  port: 8354

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: reda
    password: honggui5

mq:
  config:
    #direct
    directExchange: log.direct
    queue.info: log.info
    queue.info.routing.key: log.direct.log.info
    queue.error: log.error
    queue.error.routing.key: log.direct.log.error
    #topic
    topicLogExchange: log.topic
    topicUserExchange: user.topic
    queue.logs: log.msg
