spring:
  profiles: usage_message_sender

tutorial:
  client:
    duration: 10000

logging:
  level:
    org: ERROR

server:
  port: 8353

---
spring:
  profiles: usage_message_receiver

tutorial:
  client:
    duration: 10000

logging:
  level:
    org: ERROR

server:
  port: 8354


